/**
 * Mock LLM: no network call. Returns a deterministic "product-ish" description
 * from introspected schema so we can wire the endpoint shape now and swap later.
 */
function describeTableMock({ tableName, columns, primaryKey, indexes, rowEstimate }) {
  const columnList = columns
    .map((col) => `${col.name} (${col.dataType}${col.isNullable ? ", nullable" : ""})`)
    .join(", ");

  const pk = primaryKey.length ? primaryKey.join(", ") : "none";
  const indexList = indexes.length ? indexes.map((i) => i.name).join(", ") : "none";

  return {
    provider: "mock-llm",
    model: "mock-v1",
    summary:
      `Table "${tableName}" looks like a core entity with ~${rowEstimate} rows. ` +
      `Columns: ${columnList}. Primary key: ${pk}. Indexes: ${indexList}. ` +
      `This description is generated by a mock LLM for sprint 001; replace with a real provider later.`,
  };
}

module.exports = { describeTableMock };
